### ISSUE TITLE
I'd like to contribute to this.

### ISSUE THREAD

**Issue by konan-5** [manifold-inc/targon-stats#16]
Thank you for hard work, team
Actually, I think targon-stats is great project, but I also think a lot of UI should be updated. For example, now mobile version is not working. If possible, could you let me know how I can start to develop?

**Comment by darwich6** [comment]
PRs are always encouraged! Mobile was something we always wanted to do, just didn't have time yet!

**Comment by darwich6** [comment]
PRs are always encouraged! Mobile was something we always wanted to do, just didn't have time yet!

**Comment by konan-5** [comment]
hello @darwich6 
thank you for reply
yeah, I'd like to help mobile view

**Comment by konan-5** [comment]
in terms of environment, should I get all env by myself?
or could you provide me?

**Comment by GentikSolm** [comment]
your env file should look similar to
```
DATABASE_HOST=
DATABASE_USERNAME=
DATABASE_PASSWORD=
DATABASE_URL=

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=

HUB_API_ENDPOINT=
```
Grab database credentials from planetscale, or you can use a local mysql db with the pscale http layer, youll need to research how to set that up. Google secrets can be anything arbitrary, you just wont be able to sign in w/ google.

**Comment by GentikSolm** [comment]
We will try and make this easier for outside contributors though. Sorry its a bit chaotic as it stands.

**Comment by konan-5** [comment]
hello
how are you
thank you for your message
I will try to make PR soon
so when I have question, should I only ask here?
if possible, could we chat via discord or tg?

**Comment by GentikSolm** [comment]
https://discord.gg/Sh856RspQW
